# General pipeline options
max_threads: 20

# Input parameters
input_format: bam #fastq, pod5, bam (aligned bam), ubam (unaligned bam)
variant_calling_mode: germline #germline or somatic

# Output paramters
output_dir: /mnt/beegfs/userdata/m_aglave/long-reads-bulk/test/data_output/

# Select which parts of the pipeline should be run
steps:
  fastq_qc: false
  bam_qc: true
  snv_calling: true
  sv_calling: true
  phasing: true

# Path to design file
design: /mnt/beegfs/userdata/m_aglave/long-reads-bulk/test/script/design_bam_germline.tsv

# Genome information
#Note: genome_snpEff: GRCh38.109 doesn't exist in snpEff database
references:
  species: human
  genome_name: GRCh38.109
  genome: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.109/homo_sapiens.GRCh38.109.fasta
  minimap2_index: /mnt/beegfs/database/bioinfo/Index_DB/Fasta/Ensembl/GRCh38.109/homo_sapiens.GRCh38.109.mmi
  genome_snpEff: GRCh38.99
  dbsnp: /mnt/beegfs/database/bioinfo/Index_DB/dbNSFP/4.1/GRCh38/dbNSFP4.1a.txt.gz
  clinvar: /mnt/beegfs/database/bioinfo/Index_DB/ClinVar/GRCh38/clinvar_20230710.vcf.gz

# Clair3 parameters
clair3:
  # Latest R10 model from Rerio for Dorado SUP / downloaded on 2024-02-25
  model: ["/mnt/beegfs/userdata/n_rabearivelo/rerio/clair3_models/r1041_e82_400bps_sup_v430"]

snpsift:
  filters: ["(FILTER = 'PASS')", "( QUAL >= 10 )", "( QUAL >= 15 )"]

# ClairS parameters
clairs:
  model: ont_r10_dorado_sup_5khz
